services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users
      - products
    restart: unless-stopped
  
  users:
    build: ./services/users
    env_file:
      - ./services/users/.env
    ports:
      - "8001:8000"    # accessible only to other containers
    restart: unless-stopped
    
  products:
    build: ./services/products
    env_file:
      - ./services/products/.env
    ports:
      - "8002:8000"
    restart: unless-stopped
