apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  ENV: {{ .Values.env.ENV | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET | quote }}
  GOOGLE_REDIRECT_URI : {{ .Values.env.GOOGLE_REDIRECT_URI | quote }}
  REDIS_URL : {{ .Values.env.REDIS_URL | quote }}
  GITHUB_CLIENT_ID : {{ .Values.env.GITHUB_CLIENT_ID | quote }}
  GITHUB_CLIENT_SECRET : {{ .Values.env.GITHUB_CLIENT_SECRET | quote }}
  GITHUB_REDIRECT_URI : {{ .Values.env.GITHUB_REDIRECT_URI | quote }}