apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
        sendfile on;
        keepalive_timeout 65;

        upstream users_service {
            server users-service:8000;
        }

        upstream products_service {
            server products-service:8000;
        }

        server {
            listen 80;

            location /users/ {
                proxy_pass http://users_service;
            }

            location /products/ {
                proxy_pass http://products_service;
            }
        }
    }
