apiVersion: v1
kind: Secret
metadata:
  name: products-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  ENV: {{ .Values.env.ENV | quote }}
  REDIS_URL : {{ .Values.env.REDIS_URL | quote }}