apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: mayascarlet31/products:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: products-secret
