apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: mayascarlet31/users:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: users-secret
