apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: users-service:latest # Change this to dockerhubusername/users:latest for remote K8 deployment
          imagePullPolicy: Never  # Comment this for remote K8 deployment. It will allow k8 to fetch docker images from dockerhub (remote)
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: users-secret
